name: Push to Dockerhub and Deploy to EC2

on:
  push:
    branches: ["stable", "bare-metal-deployment"]

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment: bare-metal-environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log environment image name and registry
        run: |
          echo ${{ env.IMAGE_NAME }}
          echo ${{ env.REGISTRY }}
      
      - name: Log in to dockerhub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Get tags for docker image
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest #
          labels: ${{ steps.meta.outputs.labels }}

      - name: SSH into server and setup env file and deploy.
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            echo "Creating .env file for docker compose"
            echo -e "
            APP_NAME=${{ secrets.APP_NAME }}\n
            APP_ENV=${{ secrets.APP_ENV }}\n  
            HTTP_URL=${{ secrets.HTTP_URL }}\n
            HTTP_PORT=${{ secrets.HTTP_PORT }}\n
            HTTP_ALLOWED_ORIGINS=${{ secrets.HTTP_ALLOWED_ORIGINS }}\n
            DB_CONNECTION=${{ secrets.DB_CONNECTION }}\n
            DB_PORT=${{ secrets.DB_PORT }}\n
            DB_NAME=${{ secrets.DB_NAME }}\n
            DB_USER=${{ secrets.DB_USER }}\n
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}\n
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}\n
            TOKEN_DURATION=${{ secrets.TOKEN_DURATION }}\n
            " > .env.prod

            echo "Installing Git"
            sudo yum install -y git
            echo "Done installing Git"

            echo "Cloning git repo"
            git clone http://github.com/${{ github.repository }}.git

            echo "Installing docker"
            sudo yum install -y docker
            echo "Docker installation complete"

            echo "Install docker compose plugin for docker"
            sudo yum install -y docker-compose-plugin
            
            docker compose --version
            echo "Docker compose installed successfully."

            echo "Stop all running containers"
            docker compose down

            echo "Restart the containers"
            docker compose --env-file ../.env.prod up --build 
